import test from "node:test";
import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { PGlite } from "@electric-sql/pglite";
test("Drive jobs are scoped, leased, private and finalize atomically after sharing",async()=>{
  const db=new PGlite();
  try {
    await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
      create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema public,auth to authenticated,anon;
      alter default privileges in schema public grant all on tables to authenticated,anon;`);
    for(const file of (await readdir("supabase/migrations")).filter(f=>f.endsWith(".sql")).sort())
      await db.exec((await readFile(`supabase/migrations/${file}`,"utf8")).replace("create extension if not exists pgcrypto;",""));
    const player=randomUUID(),other=randomUUID(),court=randomUUID(),recorder=randomUUID(),camera=randomUUID(),session=randomUUID();
    await db.query("insert into auth.users(id) values($1),($2)",[player,other]);
    await db.query("insert into public.courts(id,name) values($1,'Court')",[court]);
    await db.query("insert into public.recorders(id,name) values($1,'Recorder')",[recorder]);
    await db.query("insert into public.cameras(id,recorder_id,name,source_type,device_reference) values($1,$2,'Camera','usb','usb-test')",[camera,recorder]);
    await db.query("insert into public.recording_sessions(id,player_id,court_id,idempotency_key,configuration_snapshot,recipient_email,status) values($1,$2,$3,$4,'{}','player@gmail.com','local_ready')",[session,player,court,randomUUID()]);
    await db.query("insert into public.capture_jobs(session_id,recorder_id,camera_id,device_reference,max_seconds,status) values($1,$2,$3,'usb-test',60,'completed')",[session,recorder,camera]);
    const file=(await db.query<{id:string}>("insert into public.recording_files(session_id,camera_id,status,bytes,local_filename) values($1,$2,'local_ready',100,$3) returning id",[session,camera,`${session}/video.mp4`])).rows[0].id;
    await db.exec("insert into public.google_integration(owner_email,root_folder_id,refresh_token_encrypted,connected_at) values('owner@gmail.com','root12345','encrypted',now()-interval '1 day')");
    assert.equal((await db.query("select * from public.claim_drive_upload($1)",[randomUUID()])).rows.length,0);
    const job=(await db.query<any>("select * from public.claim_drive_upload($1)",[recorder])).rows[0];
    assert.equal(job.file_id,file);
    assert.equal((await db.query("select * from public.claim_drive_upload($1)",[recorder])).rows.length,0,"live lease excludes duplicate workers");
    await db.exec("update public.drive_upload_jobs set lease_until=now()-interval '1 second'");
    const reclaimed=(await db.query<any>("select * from public.claim_drive_upload($1)",[recorder])).rows[0];
    assert.notEqual(reclaimed.lease_token,job.lease_token);
    assert.equal((await db.query<any>("select public.finish_drive_upload($1,$2,'permission') as ok",[file,job.lease_token])).rows[0].ok,false);
    await assert.rejects(()=>db.query("select public.finish_drive_upload($1,$2,'permission')",[file,reclaimed.lease_token]),/not verified/);
    await db.exec("update public.drive_upload_jobs set status='sharing'");
    assert.equal((await db.query<any>("select public.finish_drive_upload($1,$2,'permission') as ok",[file,reclaimed.lease_token])).rows[0].ok,true);
    assert.equal((await db.query<any>("select status from public.recording_sessions")).rows[0].status,"ready");
    assert.equal((await db.query("select * from public.claim_drive_upload($1)",[recorder])).rows.length,0);
    await db.exec("update public.recording_files set uploaded_at=now(),expires_at=now()+interval '1 day'");
    assert.equal((await db.query("select * from public.claim_recording_email($1)",[recorder])).rows.length,0,"No mail without Gmail authorization");
    await db.exec("update public.google_integration set gmail_authorized_at=now()-interval '1 hour'");
    assert.equal((await db.query("select * from public.claim_recording_email($1)",[randomUUID()])).rows.length,0,"Recorder isolation");
    const mail=(await db.query<any>("select * from public.claim_recording_email($1)",[recorder])).rows[0];
    assert.equal(mail.file_id,file);
    assert.equal(mail.status,"sending");
    assert.equal((await db.query("select * from public.claim_recording_email($1)",[recorder])).rows.length,0,"Never duplicate a leased send");
    await db.exec("update public.email_jobs set lease_until=now()-interval '1 second'");
    assert.equal((await db.query("select * from public.claim_recording_email($1)",[recorder])).rows.length,0);
    assert.equal((await db.query<any>("select status from public.email_jobs")).rows[0].status,"unknown","Crashed sends require review");
    await db.exec("update public.email_jobs set status='pending'; update public.recording_files set expires_at=now()-interval '1 second'");
    assert.equal((await db.query("select * from public.claim_recording_email($1)",[recorder])).rows.length,0);
    assert.equal((await db.query<any>("select status from public.email_jobs")).rows[0].status,"expired");
    await db.exec("set role authenticated");
    await assert.rejects(()=>db.query("select * from public.email_jobs"),/permission denied/);
    await assert.rejects(()=>db.query("select * from public.claim_recording_email($1)",[recorder]),/permission denied/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
    assert.equal((await db.query("select * from public.recording_files")).rows.length,0);
    await assert.rejects(()=>db.query("select * from public.google_integration"),/permission denied/);
    await assert.rejects(()=>db.query("select * from public.drive_upload_jobs"),/permission denied/);
    await assert.rejects(()=>db.query("select * from public.claim_drive_upload($1)",[recorder]),/permission denied/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)",[player]);
    assert.equal((await db.query("select * from public.recording_files")).rows.length,1);
  } finally {await db.close();}
});
